version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - "yarn global add gatsby"
  pre_build:
    commands:
      - "yarn install --frozen-lockfile --production"
  build:
    commands:
      - "yarn build"
  post_build:
    commands:
      - "yarn deploy"
artifacts:
  base-directory: public
  files:
    - "**/*"
  discard-paths: yes
